site_name: Gameta
site_description: CLI for managing Metarepos.
site_author: David Lee

repo_url: https://github.com/genius-systems/gameta

theme: readthedocs

nav:
  - Home: index.md
  - Metarepos: metarepos.md
  - Command Reference:
      - 0.2: commands/0.2/commands.md
      - 0.1: commands/0.1/commands.md
  - User Guide:
      - Applying Commands: user_guide/applying_commands.md
      - Best Practices: user_guide/best_practices.md
  - About:
      - Contributing: about/contributing.md
      - License: about/license.md
      - Release Notes: about/release_notes.md